server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: demo-cloud-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: demo-cloud-ribbon
    api-b:
      path: /api-b/**
      serviceId: demo-feign